const LOGIN_ADMIN = String(process.env.NEXT_PUBLIC_LOGIN_ADMIN);
const LOGIN_CS = String(process.env.NEXT_PUBLIC_LOGIN_CS);
const LOGIN_FUNDING = String(process.env.NEXT_PUBLIC_LOGIN_FUNDING);
const LOGIN_LENDING = String(process.env.NEXT_PUBLIC_LOGIN_LENDING);
const APP_STYLE_PATH = String(process.env.NEXT_PUBLIC_APP_STYLE_PATH);

export {
  LOGIN_ADMIN,
  LOGIN_CS,
  LOGIN_FUNDING,
  LOGIN_LENDING,
  APP_STYLE_PATH,
};
